### ISSUE TITLE
VR apply

### ISSUE THREAD

**Issue by Bananaanddonuts** [jalil49/KKS_MoreAccessories#2]
Thank you for your developing, it seems not working for VR because of process skipping. Process name is currently defined as [BepInProcess("KoikatsuSunshineVR")] but may be [BepInProcess("KoikatsuSunshine_VR")].

**Comment by jalil49** [comment]
Fixed, sorry would have done this with 2.0.17 if I noticed

**Comment by jalil49** [comment]
Decided to update the release since I'm still at the bottom of the discord in Mod-Sharing-Sunshine
https://github.com/jalil49/MoreAccessories/releases/tag/2.0.17
