### ISSUE TITLE
[2.0.19] Excess Slots Not Being Trimmed When The Card Is Saved In KKS

### ISSUE THREAD

**Issue by Seikikai** [jalil49/KKS_MoreAccessories#6]
I'm Currently Having The Problem That Excess Slots Aren't Being Trimmed. Done A Test Opening The Character Creator, Adding To The Default Character +10 Accessories Slots, Saving The Character, Loading Another Character Then Loading The Default Saved Character And The 10 Extra Accessories Slots Were There. Can You Check What's Going Or If You Need, Can You Tell Me How I Can Help You To Find The Problem.

Fragment Of The Log (output_log) Created When The Test Card Was Saved In Case The War Mentioned Can Be Relevant To The Problem.
```[Debug  :Sideloader] Loading card [KoikatsuSun_F_20211128190828411_春野 千佳.png]
[Debug  :Sideloader] Sideloader marker found, external info count: 0
[Info   :Remove Cards To Recycle Bin] Moved "D:\Torrents\[ScrewThisNoise] Koikatsu Sunshine BetterRepack R2.1\UserData\chara\female\KoikatsuSun_F_20211128190828411_春野 千佳.png" to recycle bin before it was removed or overwritten.
[Debug  :Modding API] Character save: 春野 千佳
[Warning:Modding API] Tried to save card before it was loaded - KoikatsuSun_F_20211128190828411_春野 千佳.png
[Debug  :Sideloader] Reloading card [KoikatsuSun_F_20211128190828411_春野 千佳.png]
[Debug  :Sideloader] External info count: 0

**Comment by jalil49** [comment]
Already got a patch for this, thanks for reporting
